steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/svc_docker-$BUILD_ID', 'svc_docker']
    timeout: 500s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/svc_docker-$BUILD_ID']