steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/svc_docker:$BUILD_ID', 'svc_docker']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/svc_docker:$BUILD_ID']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |-
    echo "$$RSAKEY" >> ~/id_rsa_gcp;
    chmod 600 ~/id_rsa_gcp;
    cat ~/id_rsa_gcp;
    echo "$$GCRTOKEN" >> gcr_token;
    scp -i ~/id_rsa_gcp gcr_token ${_ANSIBLE_USER}@${_ANSIBLE_HOST}:
    sed -i 's/host_ip/${_ANSIBLE_HOST}/g' hosts.yml;
    sed -i 's/host_user/${_ANSIBLE_USER}/g' hosts.yml;
    sed -i 's/latest/$BUILD_ID/g' hosts.yml;
    cat hosts.yml
  secretEnv: ['RSAKEY','GCRTOKEN']
- name: 'gcr.io/$PROJECT_ID/ansible'
  entrypoint: '/usr/bin/ansible-playbook'
  args: ['-i', 'hosts.yml', 'precheck.yml']
availableSecrets:
  secretManager:
  - versionName:   projects/$PROJECT_ID/secrets/id_rsa_gcp/versions/1
    env: 'RSAKEY'
  - versionName:   projects/$PROJECT_ID/secrets/gcr_access_token/versions/3
    env: 'GCRTOKEN'

