all:
  hosts:
    instance_1:
      ansible_host: host_ip
      ansible_user: host_user
      ansible_ssh_private_key_file: ~/id_rsa_gcp
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      app_version: latest
