---
  - name: Precheck tasks
    hosts: all

    tasks:

    - name: Distribution check
      debug: msg="{{ ansible_distribution }}"
    
    - name: Install the latest version of podman-docker if it does not exist
      dnf:
        name: podman-docker
        state: latest
      become: yes

    - name: Access gcr container repo
      ansible.builtin.shell: docker login -u oauth2accesstoken -p $(cat ~/gcr_token) https://gcr.io

    - name: Pull app container with defined version
      ansible.builtin.shell: docker pull gcr.io/cloudstudy3-bc/svc_docker:{{app_version}}

    - name: Check downloaded container images
      ansible.builtin.shell: docker image ls