---
  - name: Precheck tasks
    hosts: all

    tasks:

    - name: Distribution check
      debug: msg="{{ ansible_distribution }}"
    
    - name: Install the latest version of podman-docker if it does not exist
      dnf:
        name: podman-docker
        state: latest
      become: yes

    - name: Execute the command in remote shell; stdout goes to the specified file on the remote
      ansible.builtin.shell: docker login -u oauth2accesstoken -p $(cat ~/gcr_token) https://gcr.io

    - name: Execute the command in remote shell; stdout goes to the specified file on the remote
      ansible.builtin.shell: docker pull gcr.io/cloudstudy3-bc/svc_docker:$(cat ~/build_id)

    - name: Execute the command in remote shell; stdout goes to the specified file on the remote
      ansible.builtin.shell: docker image ls