---
  - name: Precheck tasks
    hosts: all

    tasks:

    - name: Distribution check
      debug: msg="{{ ansible_distribution }}"
    
    - name: Install the latest version of podman-docker if it does not exist
      dnf:
        name: podman-docker
        state: latest
      become: yes

    - name: save gcr token
      ansible.builtin.shell: cat ~/gcr_token
      register: gcrtoken

    - name: Access gcr container repo
      ansible.builtin.shell: docker login -u oauth2accesstoken -p {{ item }} https://gcr.io
      with_items: 
        - "{{ gcrtoken }}"

    - name: Pull app container with defined version
      ansible.builtin.shell: docker pull gcr.io/cloudstudy3-bc/svc_docker:{{ app_version }}

    - name: Check downloaded container images
      ansible.builtin.shell: docker image ls